#
# Build stage
#
FROM maven:latest AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml -DskipTests=true -Pprod clean package

#
# Package stage
#
FROM openjdk:latest
COPY --from=build /home/app/target/Logistica-api.jar Logistica-api.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","Logistica-api.jar"]
